### ISSUE TITLE
requirements.txt errors

### ISSUE THREAD

**Issue by hdiwan** [adlibre/Adlibre-TMS#27]
The patch attached fixes 2 errors in requirements.txt:
1. Options to pip are not able to be embedded in requirements.txt, so I've turned the --allow-external py-dom-xpath --allow-unverified py-dom-xpath py-dom-xpath into a comment.
2. Removed xml_models as py-dom-xpath is a dead project and replaced it with lxml

**Comment by hdiwan** [comment]
diff --git a/requirements.txt b/requirements.txt
index 30c7e65..4af8d46 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -3,14 +3,13 @@ BeautifulSoup==3.2.0
 Django==1.4.2
 django-any==0.2.0
 django-pagination==1.0.7
---allow-external py-dom-xpath --allow-unverified py-dom-xpath py-dom-xpath
+# --allow-external py-dom-xpath --allow-unverified py-dom-xpath py-dom-xpath
 django-celery==3.1.16
 # should be 1.0.3
 git+https://github.com/django-recurrence/django-recurrence.git#egg=django-recurrence
 django-uni-form==0.7.0
 python-dateutil==2.1
 template-utils==0.4p2
-xml-models==0.5.1
 # Deployment
 bureaucrat
 gunicorn==18.0
@@ -18,3 +17,4 @@ dj-static
 dj-database-url==0.2.2
 pyxero==0.5.2
 mysqlclient
+lxml==3.5.0

**Comment by macropin** [comment]
This was resolved a while ago. I actually forked [py-dom-xpath](https://github.com/macropin/py-dom-xpath-redux) along with [xml-models](https://github.com/macropin/xml-models-redux). So this is now resolved.
